version: "3.7"
services:
  customer-api:
      container_name: customer-api
      image: edsoncaliman/kotlin-customer-api-aws-terraform:latest
      environment:
        TZ: "America/Sao_Paulo"
      ports:
        - "80:8080"
      restart: always
      deploy:
        resources:
          reservations:
            memory: 400M
          limits:
            memory: 1000M
      healthcheck:
        test: wget -q http://localhost:8080/actuator/health -O - | grep "{\"status\":\"UP\"}" || exit 1
        interval: 60s
        retries: 3
        start_period: 2m
        timeout: 15s
