version: '3'

services:
  customer-api:
      container_name: customer-api
      image: edsoncaliman/kotlin-customer-api-aws-terraform:latest
      environment:
        TZ: "America/Sao_Paulo"
      ports:
        - "80:8080"
      restart: always
      deploy:
        resources:
          limits:
            memory: 700M
          reservations:
            memory: 700M
